# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [59]:
# Please consult the lectures
difference = """Dimensionality is the major difference between vector and matrix.

Vectors are 1-dimensional arrays, meaning they have a single axis. 

Matrices are 2-dimensional arrays, meaning they have two axes (rows and columns)."""
print(difference)

Dimensionality is the major difference between vector and matrix.

Vectors are 1-dimensional arrays, meaning they have a single axis. 

Matrices are 2-dimensional arrays, meaning they have two axes (rows and columns).


**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [3]:
list_1 = [1,2,3,4,5]

In [4]:
# To avoid overwriting the output, please code here 
array_1 = np.array(list_1)
array_1, type(array_1)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [5]:
# To avoid overwriting the output, please code here
array_arange =np.arange(6)
array_arange

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros`**

In [6]:
# To avoid overwriting the output, please code here 
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [7]:
# To avoid overwriting the output, please code here 
zeros_matrix = np.zeros((3,4))
zeros_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [41]:
# To avoid overwriting the output, please code here
ones = np.ones(5)
print(ones)


[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [8]:
# To avoid overwriting the output, please code here 
five_tens = np.full((5),10, dtype=float)
five_tens

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [10]:
# To avoid overwriting the output, please code here 
even_array = np.arange(52,100,2)
even_array

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [11]:
# To avoid overwriting the output, please code here 
linspace_1 = np.linspace(0,1,10, retstep=True)
linspace_1

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [14]:
# To avoid overwriting the output, please code here 
vector_array_of_25 = np.arange(25)
vector_array_of_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
# To avoid overwriting the output, please code here 
vector_array_of_25.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# To avoid overwriting the output, please code here 

vector_array_of_25.shape = 5,5
vector_array_of_25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [30]:
# To avoid overwriting the output, please code here 
np.arange(0.1,2.6, 0.1).reshape(5,5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [62]:
# To avoid overwriting the output, please code here 
linspace_and_print = np.linspace(0,24,25, dtype=int).reshape(5,5)
print(linspace_and_print)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [64]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

linspace_and_arange = """linspace returns an array of evenly spaced values between two points.also step size with retstep= True. And it takes 3rd argument as no of point we want.

arange produces an array of sequential numbers within a given interval, similar to the Python range. And it takes 3rd argument as step size."""
print(linspace_and_arange)

linspace returns an array of evenly spaced values between two points.also step size with retstep= True. And it takes 3rd argument as no of point we want.

arange produces an array of sequential numbers within a given interval, similar to the Python range. And it takes 3rd argument as step size.


**15. How to generate a single random integer number using NumPy built-in function?**

In [47]:
# To avoid overwriting the output, please code here 
random_int = np.random.randint(100)
random_int

84

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [50]:
# To avoid overwriting the output, please code here 
rand_matrix = np.random.rand(7,5)
print(rand_matrix)


[[0.72495294 0.20303854 0.83162324 0.94637516 0.13850864]
 [0.84222073 0.82893733 0.86079984 0.70557063 0.51675363]
 [0.34704844 0.97245966 0.14549824 0.11159901 0.02165866]
 [0.39183714 0.92655784 0.52558981 0.23006271 0.02660952]
 [0.87071447 0.78543424 0.55523083 0.50206608 0.39073417]
 [0.37679395 0.15225875 0.46257371 0.88640983 0.68025399]
 [0.23233829 0.11715413 0.06152425 0.29805266 0.16694269]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [53]:
# To avoid overwriting the output, please code here 
identity_5 = np.identity(5)*5
identity_5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 